apiVersion: v1
description: Hadoop is a framework that allows for the distributed processing of large data sets across clusters
name: hadoop
version: 0.1.0
maintainers:
  - name: Acaleph
    email: hello@acale.ph
