
Namenode:
  Name: namenode
  Image: "uhopper/hadoop-namenode"
  ImageTag: "2.7.2"
  pullPolicy: IfNotPresent
  Replicas: 1
  Component: "namenode"
  Cpu: "100m"
  Memory: "512Mi"
  NamenodeServicePort: 8020
  NamenodeContainerPort: 8020
  HttpUiServicePort: 50070
  HttpUiContainerPort: 50070
  resources:
    limits:
      cpu: 200m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 500Mi
  persistence:
    enabled: false
    storageClass: generic
    accessMode: ReadWriteOnce
    size: 8Gi


Datanode:
  Name: datanode
  Image: "uhopper/hadoop-datanode"
  ImageTag: "2.7.2"
  pullPolicy: IfNotPresent
  Replicas: 1
  Component: "datanode"
  resources:
    limits:
      cpu: 200m
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 500Mi
  persistence:
    enabled: false
    storageClass: generic
    accessMode: ReadWriteOnce
    size: 8Gi

Httpfs:
  Name: httpfs
  Image: "uhopper/hadoop"
  ImageTag: "2.7.2"
  pullPolicy: IfNotPresent
  Replicas: 1
  Component: "httpfs"
  resources:
    limits:
      cpu: 200m
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 500Mi
  persistence:
    enabled: false
    storageClass: generic
    accessMode: ReadWriteOnce
    size: 8Gi
