apiVersion: v1
kind: ConfigMap
metadata:
  name: rookd-discovery
  labels:
    app: rook
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  discovery-token: "{{ .Values.discoveryToken }}"
