# Default values for cratedb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

clusterName: my-crate-cluster

image:
  repository: crate
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  web:
    name: web
    externalPort: 4200
    internalPort: 4200
  cluster:
    name: cluster
    externalPort: 4300
    internalPort: 4300
resources:
  limits:
    cpu: 200m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 1Gi
