{{- if .Values.Datanode.enabled }}
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: hadoop-datanode
  labels:
    app: hadoop
    daemon: datanode
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  template:
    metadata:
      name: hadoop-datanode
      labels:
        app: hadoop
        daemon: datanode
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
#      nodeSelector: hadoop
      hostNetwork: true
      volumes:
        - name: hadoop-datanode
          emptyDir: {}
      containers:
        - name: datanode
          image: "{{.Values.Datanode.Image}}:{{.Values.Datanode.ImageTag}}"
          imagePullPolicy: "{{.Values.Datanode.pullPolicy}}"
          ports:
            - name: datanode
              containerPort: 50010
            - name: webui
              containerPort: 50075
          env:
            - name: MULTIHOMED_NETWORK
              value: "0"
            - name: CLUSTER_NAME
              value: hadoop
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://hadoop-namenode.hadoop.svc.cluster.local:8020
            - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              value: "false"
            - name: HDFS_CONF_dfs_client_use_datanode_hostname
              value: "false"
            - name: HDFS_CONF_dfs_datanode_use_datanode_hostname
              value: "false"
            - name: HDFS_CONF_dfs_namenode_rpc___bind___host
              value: "0.0.0.0"
            - name: HDFS_CONF_dfs_namenode_servicerpc___bind___host
              value: "0.0.0.0"
            - name: HDFS_CONF_dfs_namenode_http___bind___host
              value: "0.0.0.0"
            - name: HDFS_CONF_dfs_namenode_https___bind___host
              value: "0.0.0.0"
          volumeMounts:
            - name: hadoop-datanode
              mountPath: /hadoop/dfs/
          livenessProbe:
              tcpSocket:
                port: 50010
              initialDelaySeconds: 120
              timeoutSeconds: 5
          readinessProbe:
              tcpSocket:
                port: 50010
              timeoutSeconds: 5
          resources:
{{ toYaml .Values.Datanode.resources | indent 12 }}
{{- end }}
