apiVersion: v1
kind: Service
metadata:
  name: hive-metastore-postgresql
  labels:
    app: hive
    daemon: metastore-postgresql
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: hive
    daemon: metastore-postgresql
  # type: LoadBalancer
