{{- if .Values.Hive.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hive
    daemon: server
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  name: hive-server
spec:
  ports:
  - name: "10000"
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: "10002"
    port: 10002
    protocol: TCP
    targetPort: 10002
  selector:
    app: hive
    daemon: server
{{- end }}
