apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  labels:
    app: hive
    daemon: metastore
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  ports:
  - port: 8188
    name: metastore
    protocol: TCP
    targetPort: 8188
  - port: 9083
    name: hive
    protocol: TCP
    targetPort: 9083
  selector:
    app: hive
    daemon: metastore
  # type: LoadBalancer
