apiVersion: v1
kind: Service
metadata:
  name: hadoop-httpfs
  labels:
    app: hadoop
    daemon: httpfs
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 14000
  selector:
    app: hadoop
    daemon: httpfs
  # type: LoadBalancer
