apiVersion: v1
kind: Service
metadata:
  name: {{ template "namenode-fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Namenode.Component}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  ports:
    - name: namenode
      port: {{.Values.Namenode.NamenodeServicePort}}
      targetPort: {{.Values.Namenode.NamenodeContainerPort}}
    - name: http-ui
      port: {{.Values.Namenode.HttpUiServicePort}}
      targetPort: {{.Values.Namenode.HttpUiContainerPort}}
  selector:
    component: "{{.Release.Name}}-{{.Values.Namenode.Component}}"
