{{- if .Values.Namenode.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode
  labels:
    app: hadoop
    daemon: namenode
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  ports:
  - port: 80
    name: webui
    protocol: TCP
    targetPort: 50070
  - port: 8020
    name: namenode
    protocol: TCP
    targetPort: 8020
  selector:
    app: hadoop
    daemon: namenode
  # type: LoadBalancer
{{- end }}
