{{- if .Values.Nodemanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: hadoop-nodemanager
  labels:
    app: hadoop
    daemon: nodemanager
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  ports:
  - port: 8042
    name: webui
    protocol: TCP
    targetPort: 8042
  selector:
    app: hadoop
    daemon: nodemanager
  # type: LoadBalancer
{{- end }}
