apiVersion: v1
kind: Service
metadata:
  name: hadoop-resourcemanager
  labels:
    app: hadoop
    daemon: resourcemanager
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  ports:
  - port: 8088
    name: webui
    protocol: TCP
    targetPort: 8088
  selector:
    app: hadoop
    daemon: resourcemanager
  # type: LoadBalancer
