# Default values for presto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: smizy/presto
  tag: 0.163-alpine
  pullPolicy: IfNotPresent
service:
  name: presto
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 1Gi
